---
title: "`r params$docTitle`"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    fig_caption: false
params:
    docTitle: "BRICK calibration report"
    cal: "BRICK_calibration_report.csv"
    outputDir: "."
    scenNames: NULL
    savePlots: FALSE
    name: ""
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(mip)
library(readr)

knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = FALSE
)
```


```{r set variables and functions, check existence of first file}
filePath <- file.path(params$outputDir, params$cal)

if (!file.exists(filePath[1])) {
  print("No BRICK_calibration_report.csv file found. BRICK_calibration_calibration.csv is normally produced during calibration runs.")
  knitr::knit_exit()
}

if (!is.null(params$scenNames)) {
  names(filePath) <- params$scenNames
}
savePl <- params$savePlots
nameAdd <- params$name

.extractVariable <- function(df, varName) {
  df %>%
    filter(.data[["variable"]] == varName) %>%
    select(where(~ any(!is.na(.x))))
}

# TODO: Combine these two functions - or maybe all three - in one
.expandYToZero <- function(pl) {
  pl + expand_limits(y = 0)
}

.savePlot <- function(pl, savePl, path, nameAdd, name) {
  if (isTRUE(savePl)) {
    ggsave(file.path(path, paste0(paste(name, nameAdd, sep = "_"), ".png")), pl)
  }
  return(pl)
}

```

## Target function

```{r load data}

if (length(filePath) == 1) {
  data <- read_csv(filePath)
  
  color <- NULL
} else if (length(filePath) > 1) {
  data <- data.frame()
  for (scen in names(filePath)) {
    tmp <- read_csv(filePath[[scen]]) %>%
      mutate(scenario = scen, .before = 1)
    data <- rbind(data, tmp)
  }
  
  color <- "scenario"
}

```

```{r target function}

.savePlot(lapply(mipIterations(.extractVariable(data, "targetFunction"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "targetFunction")


```

## Absolute stock and flow deviation

Absolute aggregate deviations of flows and stocks

```{r absolute stock and flow deviations}
.savePlot(lapply(mipIterations(.extractVariable(data, "stockDevAgg"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "stockDevAgg")

.savePlot(lapply(mipIterations(.extractVariable(data, "conDevAgg"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "conDevAgg")

.savePlot(lapply(mipIterations(.extractVariable(data, "renDevAgg"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "renDevAgg")

.savePlot(lapply(mipIterations(.extractVariable(data, "flowDevAgg"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "flowDevAgg")

```


## Relative stock and flow deviation

Relative aggregate deviations of flows and stocks

```{r relative stock and flow deviation}
.savePlot(lapply(mipIterations(.extractVariable(data, "stockDevRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "stockDevRel")

.savePlot(lapply(mipIterations(.extractVariable(data, "conDevRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "conDevRel")

.savePlot(lapply(mipIterations(.extractVariable(data, "renDevRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "renDevRel")

.savePlot(lapply(mipIterations(.extractVariable(data, "flowDevRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "flowDevRel")

```

## Absolute deviations by hs

Absolute deviations by hs.

```{r absolute stock and flow deviation by hs}
.savePlot(lapply(mipIterations(.extractVariable(data, "stockDevHs"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "stockDevHs")
.savePlot(lapply(mipIterations(.extractVariable(data, "conDevHs"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "conDevHs")
.savePlot(lapply(mipIterations(.extractVariable(data, "renDevHs"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "renDevHs")
.savePlot(lapply(mipIterations(.extractVariable(data, "flowDevHs"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "flowDevHs")
```

## Relative deviation by hs

Relative deviations by hs.

```{r relative stock and flow deviation by hs}
.savePlot(lapply(mipIterations(.extractVariable(data, "stockDevHsRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "stockDevHsRel")

.savePlot(lapply(mipIterations(.extractVariable(data, "flowDevHsRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "flowDevHsRel")

.savePlot(lapply(mipIterations(.extractVariable(data, "conDevHsRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "conDevHsRel")
.savePlot(lapply(mipIterations(.extractVariable(data, "renDevHsRel"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = "hsr", facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "renDevHsRel")
```

## Step size

```{r step size}

.savePlot(lapply(mipIterations(.extractVariable(data, "stepSize"),
                               returnGgplots = TRUE,
                               xAxis = "iteration", color = color, facets = c("typ", "loc"),
                               slider = NULL, facetScales = "free"),
                 .expandYToZero),
          savePl, dirname(filePath[1]), nameAdd, "stepSize")

```

